from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response

from .models import (
    User, Song, Library, SongPrompt,
    AIGenerationRequest, SharedSong, PlaybackSession, Draft,
)
from .serializers import (
    UserSerializer, SongSerializer, LibrarySerializer, SongPromptSerializer,
    AIGenerationRequestSerializer, SharedSongSerializer,
    PlaybackSessionSerializer, DraftSerializer,
)


class UserViewSet(viewsets.ModelViewSet):
    """
    CRUD for User.
    list   GET    /api/users/
    create POST   /api/users/
    read   GET    /api/users/{id}/
    update PUT    /api/users/{id}/
    patch  PATCH  /api/users/{id}/
    delete DELETE /api/users/{id}/
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer

    @action(detail=True, methods=['get'], url_path='songs')
    def songs(self, request, pk=None):
        """GET /api/users/{id}/songs/ — all songs generated by this user."""
        user = self.get_object()
        serializer = SongSerializer(user.songs.all(), many=True)
        return Response(serializer.data)

    @action(detail=True, methods=['get'], url_path='library')
    def library(self, request, pk=None):
        """GET /api/users/{id}/library/ — the user's library."""
        user = self.get_object()
        try:
            serializer = LibrarySerializer(user.library)
            return Response(serializer.data)
        except Library.DoesNotExist:
            return Response(
                {'detail': 'This user has no library yet.'},
                status=status.HTTP_404_NOT_FOUND,
            )


class SongViewSet(viewsets.ModelViewSet):
    """
    CRUD for Song.
    list   GET    /api/songs/
    create POST   /api/songs/
    read   GET    /api/songs/{id}/
    update PUT    /api/songs/{id}/
    patch  PATCH  /api/songs/{id}/
    delete DELETE /api/songs/{id}/
    """
    queryset = Song.objects.select_related('user', 'playback_session').all()
    serializer_class = SongSerializer

    @action(detail=True, methods=['get'], url_path='prompt')
    def prompt(self, request, pk=None):
        """GET /api/songs/{id}/prompt/ — the prompt that defined this song."""
        song = self.get_object()
        try:
            serializer = SongPromptSerializer(song.prompt)
            return Response(serializer.data)
        except SongPrompt.DoesNotExist:
            return Response(
                {'detail': 'No prompt attached to this song.'},
                status=status.HTTP_404_NOT_FOUND,
            )

    @action(detail=True, methods=['get'], url_path='drafts')
    def drafts(self, request, pk=None):
        """GET /api/songs/{id}/drafts/ — all saved drafts of this song."""
        song = self.get_object()
        serializer = DraftSerializer(song.drafts.all(), many=True)
        return Response(serializer.data)


class LibraryViewSet(viewsets.ModelViewSet):
    """
    CRUD for Library.
    list   GET    /api/libraries/
    create POST   /api/libraries/
    read   GET    /api/libraries/{id}/
    update PUT    /api/libraries/{id}/
    patch  PATCH  /api/libraries/{id}/
    delete DELETE /api/libraries/{id}/
    """
    queryset = Library.objects.prefetch_related('songs').select_related('user').all()
    serializer_class = LibrarySerializer

    @action(detail=True, methods=['post'], url_path='add-song')
    def add_song(self, request, pk=None):
        """POST /api/libraries/{id}/add-song/ — add a song to the library."""
        library = self.get_object()
        song_id = request.data.get('song_id')
        if not song_id:
            return Response(
                {'detail': 'song_id is required.'},
                status=status.HTTP_400_BAD_REQUEST,
            )
        try:
            song = Song.objects.get(pk=song_id)
        except Song.DoesNotExist:
            return Response(
                {'detail': 'Song not found.'},
                status=status.HTTP_404_NOT_FOUND,
            )
        library.songs.add(song)
        library.sync_total_count()
        return Response(LibrarySerializer(library).data)

    @action(detail=True, methods=['post'], url_path='remove-song')
    def remove_song(self, request, pk=None):
        """POST /api/libraries/{id}/remove-song/ — remove a song from the library."""
        library = self.get_object()
        song_id = request.data.get('song_id')
        if not song_id:
            return Response(
                {'detail': 'song_id is required.'},
                status=status.HTTP_400_BAD_REQUEST,
            )
        try:
            song = Song.objects.get(pk=song_id)
        except Song.DoesNotExist:
            return Response(
                {'detail': 'Song not found.'},
                status=status.HTTP_404_NOT_FOUND,
            )
        library.songs.remove(song)
        library.sync_total_count()
        return Response(LibrarySerializer(library).data)


class SongPromptViewSet(viewsets.ModelViewSet):
    """
    CRUD for SongPrompt.
    list   GET    /api/song-prompts/
    create POST   /api/song-prompts/
    read   GET    /api/song-prompts/{id}/
    update PUT    /api/song-prompts/{id}/
    patch  PATCH  /api/song-prompts/{id}/
    delete DELETE /api/song-prompts/{id}/
    """
    queryset = SongPrompt.objects.select_related('song').all()
    serializer_class = SongPromptSerializer


class AIGenerationRequestViewSet(viewsets.ModelViewSet):
    """
    CRUD for AIGenerationRequest.
    list   GET    /api/generation-requests/
    create POST   /api/generation-requests/
    read   GET    /api/generation-requests/{id}/
    update PUT    /api/generation-requests/{id}/
    patch  PATCH  /api/generation-requests/{id}/
    delete DELETE /api/generation-requests/{id}/
    """
    queryset = AIGenerationRequest.objects.select_related('prompt').all()
    serializer_class = AIGenerationRequestSerializer


class SharedSongViewSet(viewsets.ModelViewSet):
    """
    CRUD for SharedSong.
    list   GET    /api/shared-songs/
    create POST   /api/shared-songs/
    read   GET    /api/shared-songs/{id}/
    update PUT    /api/shared-songs/{id}/
    patch  PATCH  /api/shared-songs/{id}/
    delete DELETE /api/shared-songs/{id}/
    """
    queryset = SharedSong.objects.select_related('song').all()
    serializer_class = SharedSongSerializer


class PlaybackSessionViewSet(viewsets.ModelViewSet):
    """
    CRUD for PlaybackSession.
    list   GET    /api/playback-sessions/
    create POST   /api/playback-sessions/
    read   GET    /api/playback-sessions/{id}/
    update PUT    /api/playback-sessions/{id}/
    patch  PATCH  /api/playback-sessions/{id}/
    delete DELETE /api/playback-sessions/{id}/
    """
    queryset = PlaybackSession.objects.all()
    serializer_class = PlaybackSessionSerializer


class DraftViewSet(viewsets.ModelViewSet):
    """
    CRUD for Draft.
    list   GET    /api/drafts/
    create POST   /api/drafts/
    read   GET    /api/drafts/{id}/
    update PUT    /api/drafts/{id}/
    patch  PATCH  /api/drafts/{id}/
    delete DELETE /api/drafts/{id}/
    """
    queryset = Draft.objects.select_related('song').all()
    serializer_class = DraftSerializer
